name: Docker Image Builder

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build_on_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth
          - backend
          - frontend    
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: "fetch-depth:2"

      - name: Determine changed services
        id: changed_files
        run: |
          if [[ $(git diff --name-only HEAD $(git merge-base HEAD main)) == *"${{matrix.service}}"* ]]; then
            echo "::set-output name=service_changed::true"
          else
            echo "::set-output name=service_changed::false"
          fi
  
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
  
      - name: Build Docker image
        if: steps.changed_files.outputs.service_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{matrix.service}}:latest
          context: ${{matrix.service}}
