name: Docker Image Builder

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build_on_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth
          - backend
          - frontend    
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
  
      - name: Determine changed services
        id: changed_files
        run: |
          echo "::set-output name=services::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^(auth|backend|frontend)' | uniq)"
  
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker images
        id: docker_build
        run: |
          for service in ${{ steps.changed_files.outputs.services }}; do
            docker build -f $service/Dockerfile -t $service:latest .  
          done
