name: Docker Image Builder

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build_on_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth
          - backend
          - frontend    
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: "fetch-depth:2"
          ref: "refs/heads/main" # Fetch main branch from origin repository

      - name: Get changed directories from main branch
        id: changed-dirs-main
        run: |
          git fetch origin main
          git diff --name-only FETCH_HEAD | xargs dirname | sort -u > changed-dirs-main.txt

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check for service directory changes and build Docker image based on main branch comparison
        id: check-and-build-image-main
        run: |
          if grep -q "${{ matrix.service }}" changed-dirs-main.txt; then
            echo "Build ${{ matrix.service }} Docker image"
            docker build -t ${{ matrix.service }} .
          else 
            echo "No changes in ${{ matrix.service }} directory based on main branch comparison. Skipping image build."
          fi

