name: Docker Image Builder

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth
          - backend
          - frontend    

    steps:
      - name: Checkout code with submodules
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        id: docker_build
        run: | 
          docker build -f ${{ matrix.service }}/Dockerfile -t ${{ matrix.service }}:latest .  
